flowers/flowers_base/urls.py
# coding=utf-8
"""
================================================================

author: Tan Chang 
file: urls.py
date:2023/12/19

================================================================
"""

from django.urls import path
from . import views

app_name = "flowers_base"

urlpatterns = [
    path('', views.index, name="index"),  # 主页路由
    path('flower_data/', views.flowers_data, name="flower_data"),  # flower_data界面的路由
    path('flower_class/', views.flowerClass, name="flower_class"),  # flower_class界面路由
    path('admin_data/', views.adminData, name="admin_data"), # 管理员界面路由
    path('add_flower', views.add_flower, name="add_flower"),  # 添加Flower的form表单路由
    path('add_flowerclass', views.add_flowerclass, name="add_flowerclass"),  # 添加Flower class的form表单路由
    path('add_admin', views.add_admin, name="add_admin"),  # 添加Flower class的form表单路由
    path('edit_flower/<int:flower_id>/', views.edit_flower, name="edit_flower"), # 编辑花的信息的路由
    path('delete_flower/<int:flower_id>/', views.delete_flower, name="delete_flower"), # 删除花的信息
    path('class_flower/<int:class_id>/', views.class_flower, name="class_flower"), #花的类别
    path('search/', views.search_flower, name="search_flower"), #查询功能
    path('delete_class/<int:class_id>/', views.delete_class, name="delete_class"), #删除花的类别
    path('edit_class/<int:class_id>/', views.edit_class, name="edit_class"),  #修改花的类别
    path('edit_admin/<int:admin_id>/', views.edit_admin, name="edit_admin"),    #修改管理员的信息
    path('delete_admin/<int:admin_id>/', views.delete_admin, name="delete_admin"),  #删除管理员信息
    path('search_surplus/', views.search_surplus, name="search_surplus"),
]

flowers/flowers_manage_systemctl/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #flowers_base项目中的路由
    path('',include('flowers_base.urls')),
    path('flowers_transcaction',include('flowers_transcaction.urls'))
]

flowers/flowers_transcaction/urls.py
# conding:utf-8
"""
#Time: 2023/12/19-15:12
#Author: tanchang
#File: urls.py
#Project: 鲜花库存管理系统
#Text: GoodGood学习！天天UpUp
"""


from django.urls import path
from . import views

app_name = 'flowers_transcaction'

urlpatterns = [
    path('inbound/<int:flower_id>', views.inbound_list, name='inbound'), #入库表视图
    path('outbound/<int:flower_id>', views.outbound_list, name='outbound'), #出库表视图
    path('bound_list/<int:admin_id>',views.admin_bond_list, name='admin_bond_list'), #管理员操作出库入库视图
    path('delete_inbound_data/<int:inbound_id>',views.delete_inbound, name='delete_inbound'), #删除入库视图
    path('delete_outbound_data/<int:outbound_id>',views.delete_outbound, name='delete_outbound'),
    path('bound_list/',views.bond_list, name='bound_list'), #整体出库入库表视图
    # path('in_bound_list/',views.in_bond_list, name='in_bound_list'),
]

flowers/flowers_base/models.py
from django.db import models


# Create your models here.

# 鲜花类别模型
class flower_class(models.Model):
    # 定义类别号、类别名称
    class_id = models.IntegerField(primary_key=True, unique=True)
    class_name = models.CharField(max_length=30, unique=True)
    #显示类别名字
    def __str__(self):
        return self.class_name


# 定义鲜花模型
class flower_data(models.Model):
    # 定义编号、名称、类别号、单价、库存数
    flower_id = models.IntegerField(primary_key=True, unique=True)
    flower_name = models.CharField(max_length=20, unique=True)
    # 设置外键指向flower_class，如果flower_class删除关于这个类别的所有鲜花也都删除
    classi = models.ForeignKey(flower_class,to_field="class_id", on_delete=models.CASCADE)
    price = models.DecimalField(null=True, max_digits=15, decimal_places=2)
    num = models.IntegerField()

    #显示flower的名字
    def __str__(self):
        return self.flower_name


# 管理员模型
class admin_data(models.Model):
    # 定义管理员工号、姓名、电话
    admin_id = models.IntegerField(primary_key=True, unique=True)
    admin_name = models.CharField(max_length=30)
    telephone = models.CharField(max_length=30, null=True)
    #显示管理员的名字
    def __str__(self):
        return self.admin_name

flowers/flowers_base/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib import messages
from .models import flower_data, flower_class, admin_data
from .form import FlowersForm, FlowerClassForm, adminForm, SearchForm
import re
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import uuid
from flowers_transcaction.models import inbound,outbound

# Create your views here.

# 主页视图urls.py文件中指向
def index(request):
    return render(request, 'flowers_base/index.html')


# flower_data的视图方法
def flowers_data(request):
    flowers = flower_data.objects.order_by('flower_id')  # 获取数据库中的数据，并且按照flower_id来排序
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(flowers, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
    }  # 在html文件中将flowers直接映射为flowers，在render中调用了
    return render(request, 'flowers_base/flowers_data.html', context)


#flower类别视图
def flowerClass(request):
    class_data = flower_class.objects.order_by('class_id')
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(class_data, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
    }
    return render(request, 'flowers_base/class_data.html', context)

#管理员用户视图
def adminData(request):
    admindata = admin_data.objects.order_by('admin_id')
    page_number = request.GET.get('page', 1)  ## 页码
    paginator = Paginator(admindata, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
    }
    return render(request, 'flowers_base/admin_data.html', context)


# 向数据库中添加flower的方法
def add_flower(request):
    if request.method != 'POST':  # 如果不是POST请求就创建一个空表单，请求一般是get请求
        form = FlowersForm(initial={'flower_id': str(uuid.uuid4())})
        print(form)
    else:
        form = FlowersForm(data=request.POST)
        if form.is_valid():

            form.save()
            return redirect('flowers_base:flower_data')
    context = {'form': form}
    return render(request, 'flowers_base/add_flower.html', context)


# 添加鲜花类视图
def add_flowerclass(request):
    if request.method != 'POST':  # 如果不是POST请求就创建一个空表单，请求一般是get请求
        form = FlowerClassForm()
    else:
        form = FlowerClassForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('flowers_base:flower_class')
    context = {'form': form}
    return render(request, 'flowers_base/add_flowerclass.html', context)


## 添加管理员视图
def add_admin(request):
    if request.method != 'POST':
        form = adminForm()
    else:
        form = adminForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('flowers_base:admin_data')
    context = {'form': form}
    return render(request, 'flowers_base/add_admin.html', context)

#修改花的信息
def edit_flower(request, flower_id):
    flower = flower_data.objects.get(flower_id=flower_id)
    clas = flower.classi
    if request.method != 'POST':
        form = FlowersForm(instance=flower)
    else:
        # fl = int(request.POST.get('flower_id'))
        form = FlowersForm(instance=flower, data=request.POST)
        # if fl == flower_id:
        if form.is_valid():
            #检测用户是否修改了flower_name
            # if 'flower_id' in request.POST:
            form.save()
            return redirect('flowers_base:flower_data',)
        # else:
        #     messages.error(request, "flower_id不能被修改")
    context = {'form': form, "clas": clas, "flower": flower}
    return render(request, 'flowers_base/edit_flower.html', context)



#修改花的类别信息
def edit_class(request, class_id):
    class_i = flower_class.objects.get(class_id=class_id)
    if request.method != 'POST':
        form = FlowerClassForm(instance=class_i)
    else:
        # ci = int(request.POST.get('class_id'))
        form = FlowerClassForm(instance=class_i, data=request.POST)
        # if ci == class_id: #检查是否修改了class_id
        if form.is_valid():
            form.save()
            return redirect('flowers_base:flower_class')
        # else: ##如果修改了就报错
        #     messages.error(request, "class_id不能被修改")
    context = {'form':form, "class_i": class_i}
    return render(request, 'flowers_base/edit_class.html', context)


#修改管理员信息
def edit_admin(request, admin_id):
    admin = admin_data.objects.get(admin_id=admin_id)
    if request.method != 'POST':
        form = adminForm(instance=admin)
    else:
        # admini = int(request.POST.get("admin_id"))
        form = adminForm(instance=admin, data=request.POST)
        # if admin_id != admini:  # 检查是否修改了admin_id
        #     messages.error(request, "admin_id不能被修改")
        # else:
        if form.is_valid():
            form.save()
            return redirect('flowers_base:admin_data')
    context = {'form':form, "admin": admin}
    return render(request, 'flowers_base/edit_admin.html', context)

# 删除鲜花视图
def delete_flower(request, flower_id):
    flower_id = flower_data.objects.get(flower_id=flower_id)
    flower_id.delete()
    return redirect('flowers_base:flower_data')

#删除花类别视图
def delete_class(request, class_id):
    class_id = flower_class.objects.get(class_id=class_id)
    class_id.delete()
    return redirect('flowers_base:flower_class')

#删除管理员视图
def delete_admin(request, admin_id):
    admin = admin_data.objects.get(admin_id=admin_id)
    admin.delete()
    return redirect('flowers_base:admin_data',)


#在flower_class界面中点击花的类别名就可以查看花的分类
def class_flower(request, class_id):
    flower = flower_data.objects.filter(classi=class_id)
    class_name = None
    if flower.exists():
        class_name = flower[0].classi.class_name
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(flower, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
        'class_id':class_id
    }
    return render(request, 'flowers_base/class_flower_list.html', context)


#搜索视图用法（本来想做全部搜索的，也就是admin，class也加进去,先把视图搜索，后面数据导入到HTML构思半天没构思好，先放着）
def search_flower(request):
    #获取值，这个值是input输入的内容，其中select是input输入框的name
    form = request.GET.get("select",None)
    pattern = "^[0-9]+$"
    #Q是表示可以使用or and这些来搜索
    if form:
        if re.match(pattern, form):
            modle1 = flower_data.objects.filter(
                Q(flower_id=form) | Q(classi=form) | Q(price=form) | Q(num=form))
            modle2 = admin_data.objects.filter(
                Q(admin_id=form)
            )
            modle3 = flower_class.objects.filter(
                Q(class_id=form)
            )
            modle = list(modle1)+list(modle2)+list(modle3)
        else:
            modle1 = flower_data.objects.filter(
                Q(flower_name__icontains=form) | Q(classi__class_name__icontains=form)).order_by('-flower_id').all()
            modle2 = admin_data.objects.filter(
                Q(admin_name__icontains=form)  | Q(telephone__icontains=form)
            )
            modle3 = flower_class.objects.filter(
                Q(class_name__icontains=form)
            )
            modle = list(modle1) + list(modle2)+list(modle3)
    else:
        modle = flower_data.objects.all().order_by('-flower_id')
    # search = flower_data.objects.filter(Q(flower_name__icontains=form) | Q(flower_id__icontains=form) |Q(classi__class_name__icontains=form))
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(modle, 10)
    page_obj = paginator.get_page(page_number)
    # if isinstance(page_obj.object_list[0], flower_data):
    #     n = 1;
    # elif isinstance(page_obj.object_list[0],flower_class):
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
        'key': form
    }
    return render(request,'flowers_base/search.html',context)


##这个是查询是否小于这个库存数
def search_surplus(request):
    form = request.GET.get('search_surplus')
    pattern = "^[0-9]+$"
    modle = flower_data.objects.all()
    if form and re.match(pattern, form):
            modle = flower_data.objects.filter(num__lt=form)
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(modle, 10)
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
    }
    return render(request,'flowers_base/search_surplus.html',context)

flowers/flowers_transcaction/views.py
from django.shortcuts import render, redirect,reverse
from django.http import HttpResponseRedirect, HttpResponse
from .form import InBoundForm, OutBoundForm
from .models import inbound,outbound
from flowers_base.models import flower_data
from django.contrib import messages

# Create your views here.

# （可用了）此处有问题，在点击入库表单无反应
#入库视图操作
def inbound_list(request, flower_id):
    # 获取flower对象，依靠传入的flower_id
    flower = flower_data.objects.get(flower_id=flower_id)
    init_data = {'flowers': flower.flower_name}     #初始化数据，点击哪个花就默认显示哪个花
    if request.method != 'POST': #判断如果不是POST提交请求，则是GET获取请求
        form = InBoundForm(initial=init_data)  # 就创建一个Form表单并给与初始化值
        form.fields['flowers'].queryset = flower_data.objects.filter(flower_id=flower_id) #限制只允许选择当前花
    else:
        form = InBoundForm(data=request.POST) #提交请求，提交写入的数据
        if form.is_valid():
            num = form.cleaned_data['inbound_num']  # 获取表单中的数据，并进行后续的处理
            flower.num += num  #将花本身的个数加上入库的个数
            flower.save()   #保存花的数据
            form.save_inbound()     #保存表单的数据
            return HttpResponseRedirect(reverse('flowers_base:flower_data'))
    context = {'form': form, "flower": flower}
    return render(request, 'flowers_transcaction/inbound.html', context)


# 出库视图操作操作同入库视图
def outbound_list(request, flower_id):
    flower = flower_data.objects.get(flower_id=flower_id)
    init_data = {'flowers': flower.flower_name}
    if request.method != 'POST':
        form = OutBoundForm(initial=init_data)
        form.fields['flowers'].queryset = flower_data.objects.filter(flower_id=flower_id)
    else:
        form = OutBoundForm(initial=init_data,data=request.POST)
        if form.is_valid():
            num = form.cleaned_data['outbound_num']  # 获取表单中的数据，并进行后续的处理
            flower.num -= num
            if flower.num < 0:
                messages.error(request, "库存数量不足")
            else:
                form.save()
                flower.save()
                return HttpResponseRedirect(reverse('flowers_base:flower_data'))
    context = {'form': form, "flower": flower}
    return render(request, 'flowers_transcaction/outbound.html', context)



#对应管理员的出库表清单
def admin_bond_list(request, admin_id):
    out = outbound.objects.filter(admin_id=admin_id)
    ino = inbound.objects.filter(admin_id=admin_id)
    admin_name = None   #首先将管理员的名字设置为None调用到html中使用if判断
    ##如果inbount内有数据就执行
    if ino.exists():
        admin_name = ino[0].admin.admin_name  # 获取管理员的名字
    ##如果outbount内有数据就执行
    if out.exists():
        admin_name = out[0].admin.admin_name  # 获取管理员的名字
    context = {'out': out, 'admin_name': admin_name,'ino':ino}
    return render(request, 'flowers_transcaction/admin_oprate_list.html', context)


#输出总的出库表
def bond_list(request):
    out = outbound.objects.order_by('outbound_date')
    ino = inbound.objects.order_by('inbound_date')
    # page_number = request.GET.get('page', 1) ## 页码
    # paginator = Paginator(out, 10)
    # page_obj = paginator.get_page(page_number)
    context = {
        # 'page_obj': page_obj,
        # 'paginator': paginator,
        # 'current_page': page_number,
        'out':out,
        'ino':ino,
    }
    return render(request, 'flowers_transcaction/bound_all_list.html', context)





#删除出库信息后，花的数据返回
def delete_inbound(request, inbound_id):
    inbound_data = inbound.objects.get(inbound_id=inbound_id)
    #获取flower对象依靠inbound_data的外键】】‘
    flower = flower_data.objects.get(flower_id=inbound_data.flowers.flower_id)
    #如果入库花的数量是大于小于或等于花现在的数量，那么就表示为正常
    if inbound_data.flowers.num >= inbound_data.inbound_num:
        flower.num -= inbound_data.inbound_num
        inbound_data.delete()
        flower.save()
        return redirect('flowers_transcaction:admin_bond_list',inbound_data.admin.admin_id  )
    else:
        messages.error(request, "不能删除！！，因为库存不足，请检查出库入库表单！！")


#删除出库信息后，数据返回
def delete_outbound(request, outbound_id):
    # 获取flower对象，依靠传入的flower_id
    outbound_data = outbound.objects.get(outbound_id=outbound_id)
    flower = flower_data.objects.get(flower_id=outbound_data.flowers.flower_id)
    flower.num += outbound_data.outbound_num
    outbound_data.delete()
    flower.save()
    return redirect('flowers_transcaction:admin_bond_list',outbound_data.admin.admin_id )

flowers/flowers_base/templates/flowers_transcaction/admin_oprate_list.html
{% extends 'flowers_base/base.html' %}
{%  block content %}
<div class="container">
    <div class="flower_table">
        <div class="text-center mt-5 mb-5">
            <h3 class="text-center">
                {% if admin_name %}
                    {{ admin_name }}管理员的鲜花出库记录
                {% else %}
                    未添加管理员的鲜花出库记录
                {% endif %}
            </h3>
        </div>
        <table class="table table-borderless text-center table-hover" border="1">
                 <thead>
                    <tr>
                        <th scope="col">出库号</th>
                        <th scope="col">出库数量</th>
                        <th scope="col">出库时间</th>
                        <th scope="col">操作员</th>
                        <th scope="col">花名</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
        {% for data in  out %}
                <tbody>
                    <tr>
                        <td scope="row"> {{ data.outbound_id }}</td>
                        {# 由于我这里遍历的变量是data，所以就是  data.flower_id#}
                        <td>
                            {{ data.outbound_num}}
                        </td>
                        <td>{{ data.outbound_date }}</td>
                        <td>{{ data.admin_id }}</td>
                        <td>{{ data.flowers_id }}</td>
                        <td>
                            <button type="button" class="btn btn-light btn-sm">
                                <a class="inbount-btn" href="{% url 'flowers_transcaction:delete_outbound' outbound_id=data.outbound_id%}">删除</a>
                            </button>
                        </td>
                    </tr>
                </tbody>
        {% empty %}
            <li>没有鲜花数据</li>
        {%  endfor %}
        </table>
{#        <div class="add_flowrs_for_class"><a href="{% url 'flowers_base:add_flower' %}">添加鲜花</a></div>#}
    </div>
    <div class="flower_table">
        <div class="text-center mt-5 mb-5">
            <h3 class="text-center">
                {% if admin_name %}
                    {{ admin_name }}管理员的鲜花入库记录
                {% else %}
                    未添加管理员的鲜花入库记录
                {% endif %}
            </h3>
        </div>
        <table class="table table-borderless text-center table-hover" border="1">
                 <thead>
                    <tr>
                        <th scope="col">入库号</th>
                        <th scope="col">入库数量</th>
                        <th scope="col">入库时间</th>
                        <th scope="col">操作员</th>
                        <th scope="col">花名</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
        {% for data in  ino %}
                <tbody>
                    <tr>
                        <td scope="row"> {{ data.inbound_id }}</td>
                        {# 由于我这里遍历的变量是data，所以就是  data.flower_id#}
                        <td>
                            {{ data.inbound_num}}
                        </td>
                        <td>{{ data.inbound_date }}</td>
                        <td>{{ data.admin_id }}</td>
                        <td>{{ data.flowers_id }}</td>
                        <td>
                            <button type="button" class="btn btn-light btn-sm">
                                <a class="inbount-btn" href="{% url 'flowers_transcaction:delete_inbound' inbound_id=data.inbound_id%}">删除</a>
                            </button>
                        </td>
                    </tr>
                </tbody>
        {% empty %}
            <li>没有鲜花数据</li>
        {%  endfor %}
        </table>
    </div>
</div>
{% endblock content %}

flowers/flowers_base/templates/flowers_transcaction/bound_all_list.html
{% extends 'flowers_base/base.html' %}
{%  block content %}
<div class="container">
    <div class="flower_table">
        <div class="text-center mt-5 mb-5">
            <h3 class="text-center">
                    鲜花出库记录
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}
            </h3>
        </div>
        <table class="table text-center table-hover" border="1">
                 <thead>
                    <tr>
                        <th scope="col">出库号</th>
                        <th scope="col">出库数量</th>
                        <th scope="col">出库时间</th>
                        <th scope="col">操作员</th>
                        <th scope="col">花名</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
        {% for data in  out %}
                <tbody>
                    <tr>
                        <td scope="row"> {{ data.outbound_id }}</td>
                        {# 由于我这里遍历的变量是data，所以就是  data.flower_id#}
                        <td>
                            {{ data.outbound_num}}
                        </td>
                        <td>{{ data.outbound_date }}</td>
                        <td>{{ data.admin_id }}</td>
                        <td>{{ data.flowers_id }}</td>
                        <td>
                            <button type="button" class="btn btn-light btn-sm">
                                <a class="inbount-btn" href="{% url 'flowers_transcaction:delete_outbound' outbound_id=data.outbound_id%}">删除</a>
                            </button>
                        </td>
                    </tr>
                </tbody>
        {% empty %}
            <li>没有鲜花出库记录</li>
        {%  endfor %}
        </table>
{#        <div class="add_flowrs_for_class"><a href="{% url 'flowers_base:add_flower' %}">添加鲜花</a></div>#}
    </div>
    <div class="flower_table">
        <div class="text-center mt-5 mb-5">
            <h3 class="text-center">
                鲜花入库记录
            </h3>
        </div>
        <table class="table text-center table-hover" border="1">
                 <thead>
                    <tr>
                        <th scope="col">入库号</th>
                        <th scope="col">入库数量</th>
                        <th scope="col">入库时间</th>
                        <th scope="col">操作员</th>
                        <th scope="col">花名</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
        {% for data in  ino %}
                <tbody>
                    <tr>
                        <td scope="row"> {{ data.inbound_id }}</td>
                        {# 由于我这里遍历的变量是data，所以就是  data.flower_id#}
                        <td>
                            {{ data.inbound_num}}
                        </td>
                        <td>{{ data.inbound_date }}</td>
                        <td>{{ data.admin_id }}</td>
                        <td>{{ data.flowers_id }}</td>
                        <td>
                            <button type="button" class="btn btn-light btn-sm">
                                <a class="inbount-btn" href="{% url 'flowers_transcaction:delete_inbound' inbound_id=data.inbound_id%}">删除</a>
                            </button>
                        </td>
                    </tr>
                </tbody>
        {% empty %}
            <li>没有鲜花入库记录</li>
        {%  endfor %}
        </table>
    </div>
</div>
{% endblock content %}

flowers/flowers_base/templates/flowers_transcaction/inbound.html
{% extends 'flowers_base/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="text-center mt-5 mb-5">
        <h3 class="text-center">{{ flower.flower_name }}入库</h3>
    </div>
    <div>
    <form action="{% url 'flowers_transcaction:inbound' flower.flower_id %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-light" name="submit">入库</button>
    </form>
    </div>
</div>
{% endblock %}

flowers/flowers_base/templates/flowers_transcaction/outbound.html
{% extends 'flowers_base/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="text-center mt-5 mb-5">
        <h3 class="text-center">{{ flower.flower_name }}出库</h3>
    </div>
    <div>
    <form action="{% url 'flowers_transcaction:outbound' flower.flower_id %}" method="post">
        {% csrf_token %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
        {% endfor %}
        {{ form|crispy }}
        <button class="btn btn-light" name="submit">出库</button>
    </form>
    </div>
</div>
{% endblock %}