flowers/flowers_base/urls.py
# coding=utf-8
"""
================================================================

author: Tan Chang 
file: urls.py
date:2023/12/19

================================================================
"""

from django.urls import path
from . import views

app_name = "flowers_base"

urlpatterns = [
    path('', views.index, name="index"),  # 主页路由
    path('flower_data/', views.flowers_data, name="flower_data"),  # flower_data界面的路由
    path('flower_class/', views.flowerClass, name="flower_class"),  # flower_class界面路由
    path('admin_data/', views.adminData, name="admin_data"), # 管理员界面路由
    path('add_flower', views.add_flower, name="add_flower"),  # 添加Flower的form表单路由
    path('add_flowerclass', views.add_flowerclass, name="add_flowerclass"),  # 添加Flower class的form表单路由
    path('add_admin', views.add_admin, name="add_admin"),  # 添加Flower class的form表单路由
    path('edit_flower/<int:flower_id>/', views.edit_flower, name="edit_flower"), # 编辑花的信息的路由
    path('delete_flower/<int:flower_id>/', views.delete_flower, name="delete_flower"), # 删除花的信息
    path('class_flower/<int:class_id>/', views.class_flower, name="class_flower"), #花的类别
    path('search/', views.search_flower, name="search_flower"), #查询功能
    path('delete_class/<int:class_id>/', views.delete_class, name="delete_class"), #删除花的类别
    path('edit_class/<int:class_id>/', views.edit_class, name="edit_class"),  #修改花的类别
    path('edit_admin/<int:admin_id>/', views.edit_admin, name="edit_admin"),    #修改管理员的信息
    path('delete_admin/<int:admin_id>/', views.delete_admin, name="delete_admin"),  #删除管理员信息
    path('search_surplus/', views.search_surplus, name="search_surplus"),
]

flowers/flowers_manage_systemctl/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #flowers_base项目中的路由
    path('',include('flowers_base.urls')),
    path('flowers_transcaction',include('flowers_transcaction.urls'))
]

flowers/flowers_transcaction/urls.py
# conding:utf-8
"""
#Time: 2023/12/19-15:12
#Author: tanchang
#File: urls.py
#Project: 鲜花库存管理系统
#Text: GoodGood学习！天天UpUp
"""


from django.urls import path
from . import views

app_name = 'flowers_transcaction'

urlpatterns = [
    path('inbound/<int:flower_id>', views.inbound_list, name='inbound'), #入库表视图
    path('outbound/<int:flower_id>', views.outbound_list, name='outbound'), #出库表视图
    path('bound_list/<int:admin_id>',views.admin_bond_list, name='admin_bond_list'), #管理员操作出库入库视图
    path('delete_inbound_data/<int:inbound_id>',views.delete_inbound, name='delete_inbound'), #删除入库视图
    path('delete_outbound_data/<int:outbound_id>',views.delete_outbound, name='delete_outbound'),
    path('bound_list/',views.bond_list, name='bound_list'), #整体出库入库表视图
    # path('in_bound_list/',views.in_bond_list, name='in_bound_list'),
]

flowers/flowers_base/models.py
from django.db import models


# Create your models here.

# 鲜花类别模型
class flower_class(models.Model):
    # 定义类别号、类别名称
    class_id = models.IntegerField(primary_key=True, unique=True)
    class_name = models.CharField(max_length=30, unique=True)
    #显示类别名字
    def __str__(self):
        return self.class_name


# 定义鲜花模型
class flower_data(models.Model):
    # 定义编号、名称、类别号、单价、库存数
    flower_id = models.IntegerField(primary_key=True, unique=True)
    flower_name = models.CharField(max_length=20, unique=True)
    # 设置外键指向flower_class，如果flower_class删除关于这个类别的所有鲜花也都删除
    classi = models.ForeignKey(flower_class,to_field="class_id", on_delete=models.CASCADE)
    price = models.DecimalField(null=True, max_digits=15, decimal_places=2)
    num = models.IntegerField()

    #显示flower的名字
    def __str__(self):
        return self.flower_name


# 管理员模型
class admin_data(models.Model):
    # 定义管理员工号、姓名、电话
    admin_id = models.IntegerField(primary_key=True, unique=True)
    admin_name = models.CharField(max_length=30)
    telephone = models.CharField(max_length=30, null=True)
    #显示管理员的名字
    def __str__(self):
        return self.admin_name

flowers/flowers_base/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib import messages
from .models import flower_data, flower_class, admin_data
from .form import FlowersForm, FlowerClassForm, adminForm, SearchForm
import re
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import uuid
from flowers_transcaction.models import inbound,outbound

# Create your views here.

# 主页视图urls.py文件中指向
def index(request):
    return render(request, 'flowers_base/index.html')


# flower_data的视图方法
def flowers_data(request):
    flowers = flower_data.objects.order_by('flower_id')  # 获取数据库中的数据，并且按照flower_id来排序
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(flowers, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
    }  # 在html文件中将flowers直接映射为flowers，在render中调用了
    return render(request, 'flowers_base/flowers_data.html', context)


#flower类别视图
def flowerClass(request):
    class_data = flower_class.objects.order_by('class_id')
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(class_data, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
    }
    return render(request, 'flowers_base/class_data.html', context)

#管理员用户视图
def adminData(request):
    admindata = admin_data.objects.order_by('admin_id')
    page_number = request.GET.get('page', 1)  ## 页码
    paginator = Paginator(admindata, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
    }
    return render(request, 'flowers_base/admin_data.html', context)


# 向数据库中添加flower的方法
def add_flower(request):
    if request.method != 'POST':  # 如果不是POST请求就创建一个空表单，请求一般是get请求
        form = FlowersForm(initial={'flower_id': str(uuid.uuid4())})
        print(form)
    else:
        form = FlowersForm(data=request.POST)
        if form.is_valid():

            form.save()
            return redirect('flowers_base:flower_data')
    context = {'form': form}
    return render(request, 'flowers_base/add_flower.html', context)


# 添加鲜花类视图
def add_flowerclass(request):
    if request.method != 'POST':  # 如果不是POST请求就创建一个空表单，请求一般是get请求
        form = FlowerClassForm()
    else:
        form = FlowerClassForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('flowers_base:flower_class')
    context = {'form': form}
    return render(request, 'flowers_base/add_flowerclass.html', context)


## 添加管理员视图
def add_admin(request):
    if request.method != 'POST':
        form = adminForm()
    else:
        form = adminForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('flowers_base:admin_data')
    context = {'form': form}
    return render(request, 'flowers_base/add_admin.html', context)

#修改花的信息
def edit_flower(request, flower_id):
    flower = flower_data.objects.get(flower_id=flower_id)
    clas = flower.classi
    if request.method != 'POST':
        form = FlowersForm(instance=flower)
    else:
        # fl = int(request.POST.get('flower_id'))
        form = FlowersForm(instance=flower, data=request.POST)
        # if fl == flower_id:
        if form.is_valid():
            #检测用户是否修改了flower_name
            # if 'flower_id' in request.POST:
            form.save()
            return redirect('flowers_base:flower_data',)
        # else:
        #     messages.error(request, "flower_id不能被修改")
    context = {'form': form, "clas": clas, "flower": flower}
    return render(request, 'flowers_base/edit_flower.html', context)



#修改花的类别信息
def edit_class(request, class_id):
    class_i = flower_class.objects.get(class_id=class_id)
    if request.method != 'POST':
        form = FlowerClassForm(instance=class_i)
    else:
        # ci = int(request.POST.get('class_id'))
        form = FlowerClassForm(instance=class_i, data=request.POST)
        # if ci == class_id: #检查是否修改了class_id
        if form.is_valid():
            form.save()
            return redirect('flowers_base:flower_class')
        # else: ##如果修改了就报错
        #     messages.error(request, "class_id不能被修改")
    context = {'form':form, "class_i": class_i}
    return render(request, 'flowers_base/edit_class.html', context)


#修改管理员信息
def edit_admin(request, admin_id):
    admin = admin_data.objects.get(admin_id=admin_id)
    if request.method != 'POST':
        form = adminForm(instance=admin)
    else:
        # admini = int(request.POST.get("admin_id"))
        form = adminForm(instance=admin, data=request.POST)
        # if admin_id != admini:  # 检查是否修改了admin_id
        #     messages.error(request, "admin_id不能被修改")
        # else:
        if form.is_valid():
            form.save()
            return redirect('flowers_base:admin_data')
    context = {'form':form, "admin": admin}
    return render(request, 'flowers_base/edit_admin.html', context)

# 删除鲜花视图
def delete_flower(request, flower_id):
    flower_id = flower_data.objects.get(flower_id=flower_id)
    flower_id.delete()
    return redirect('flowers_base:flower_data')

#删除花类别视图
def delete_class(request, class_id):
    class_id = flower_class.objects.get(class_id=class_id)
    class_id.delete()
    return redirect('flowers_base:flower_class')

#删除管理员视图
def delete_admin(request, admin_id):
    admin = admin_data.objects.get(admin_id=admin_id)
    admin.delete()
    return redirect('flowers_base:admin_data',)


#在flower_class界面中点击花的类别名就可以查看花的分类
def class_flower(request, class_id):
    flower = flower_data.objects.filter(classi=class_id)
    class_name = None
    if flower.exists():
        class_name = flower[0].classi.class_name
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(flower, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
        'class_id':class_id
    }
    return render(request, 'flowers_base/class_flower_list.html', context)


#搜索视图用法（本来想做全部搜索的，也就是admin，class也加进去,先把视图搜索，后面数据导入到HTML构思半天没构思好，先放着）
def search_flower(request):
    #获取值，这个值是input输入的内容，其中select是input输入框的name
    form = request.GET.get("select",None)
    pattern = "^[0-9]+$"
    #Q是表示可以使用or and这些来搜索
    if form:
        if re.match(pattern, form):
            modle1 = flower_data.objects.filter(
                Q(flower_id=form) | Q(classi=form) | Q(price=form) | Q(num=form))
            modle2 = admin_data.objects.filter(
                Q(admin_id=form)
            )
            modle3 = flower_class.objects.filter(
                Q(class_id=form)
            )
            modle = list(modle1)+list(modle2)+list(modle3)
        else:
            modle1 = flower_data.objects.filter(
                Q(flower_name__icontains=form) | Q(classi__class_name__icontains=form)).order_by('-flower_id').all()
            modle2 = admin_data.objects.filter(
                Q(admin_name__icontains=form)  | Q(telephone__icontains=form)
            )
            modle3 = flower_class.objects.filter(
                Q(class_name__icontains=form)
            )
            modle = list(modle1) + list(modle2)+list(modle3)
    else:
        modle = flower_data.objects.all().order_by('-flower_id')
    # search = flower_data.objects.filter(Q(flower_name__icontains=form) | Q(flower_id__icontains=form) |Q(classi__class_name__icontains=form))
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(modle, 10)
    page_obj = paginator.get_page(page_number)
    # if isinstance(page_obj.object_list[0], flower_data):
    #     n = 1;
    # elif isinstance(page_obj.object_list[0],flower_class):
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
        'key': form
    }
    return render(request,'flowers_base/search.html',context)


##这个是查询是否小于这个库存数
def search_surplus(request):
    form = request.GET.get('search_surplus')
    pattern = "^[0-9]+$"
    modle = flower_data.objects.all()
    if form and re.match(pattern, form):
            modle = flower_data.objects.filter(num__lt=form)
    page_number = request.GET.get('page', 1) ## 页码
    paginator = Paginator(modle, 10)
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'paginator': paginator,
        'current_page': page_number,
    }
    return render(request,'flowers_base/search_surplus.html',context)

flowers/flowers_base/templates/flowers_base/base.html
{#主模板#}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>base</title>
    {% load django_bootstrap5 %}
    {% load custom_tags %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'flower_base\css\index_nav.css' %}">
</head>
<body>
{#导航栏设置#}
<nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary" style="background-color:  #181717;">
    <div class="container-fluid">
        <a class="navbar-brand" style="color: white" href="#">鲜花库存管理系统</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse nav_daohan" id="navbarNav">
            <ul class=" nav nav-tabs">
                {# 在主页中显示的几个选项，点击可以跳转到相应界面  #}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" aria-current="page" href="{% url 'flowers_base:index' %}">flower base</a>#}
{#                </li>#}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'flowers_base:flower_data' %}">鲜花数据</a> </li>
                <li class="nav-item">
                    <a class="nav-link"  href="{% url 'flowers_base:flower_class' %}">鲜花类别数据</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'flowers_base:admin_data' %}">管理员数据</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'flowers_transcaction:bound_list' %}">出库入库数据</a>
                </li>
            </ul>
            <div class="row mx-auto">
                <form class="d-flex " role="search" action="{% url 'flowers_base:search_flower' %}" method="get">
                    <div class="mx-auto input-group">
                        <input class="form-control form-control-sm" aria-label="Search" type="text" name="select" placeholder="搜索">
                        <button class="btn btn-outline-light btn-sm mx-2" type="submit">搜索</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</nav>
    <div>
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

flowers/flowers_base/templates/flowers_base/edit_admin.html
{% extends 'flowers_base/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="text-center mt-5 mb-5">
            <h3 class="text-center">修改管理员{{ admin.admin_name }}信息</h3>
        </div>
        <div class="edit_flower_form">
            <form  class="form-horizontal" action="{% url 'flowers_base:edit_admin' admin.admin_id %}" method="post">
                {% csrf_token %}

                {{ form|crispy }}
                <button class="btn btn-light" name="submit">修改信息</button>
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}
{#                 我直接将删除和编辑做在一起了#}
                <button class="btn btn-light" name="submit">
                    <a class="edit_a" href="{% url 'flowers_base:delete_admin' admin_id=admin.admin_id %}">删除此条数据</a>
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

flowers/flowers_base/templates/flowers_base/flowers_data.html
{% extends 'flowers_base/base.html' %}
{% load static %}
{%  block content %}
    <div class="container">
        <div class="text-center mt-2 mb-2">
            <h3 class="text-center">鲜花库存数据表</h3>
        </div>
        <div class="row mx-auto search_surplus_start">
            <div class="col-6 d-flex justify-content-start mb-1 search_surplus_form ">

                    <form class="d-flex" role="search" action="{% url 'flowers_base:search_surplus' %}" method="get">
                        <div class="input-group">
                            <input class="form-control  form-control-sm" aria-label="Search" type="text" name="search_surplus" placeholder="输入剩余数量">
                            <button class="btn btn-outline-success btn-sm" type="submit" >搜索</button>
                        </div>
                    </form>
                </div>
            <div class="col-6 d-flex justify-content-end mb-1  add_flower_btn">
                <div class="add_flowers">
                    <button class="btn btn-light btn-sm">
                        <a class="add_flowers_a" href="{% url 'flowers_base:add_flower' %}">添加鲜花</a>
                    </button>
                </div>
            </div>
        </div>
        <div class="container">
            <table class="table text-center table-hover" border="1">
                     <thead>
                        <tr>
                            <th scope="col">编号</th>
                            <th scope="col">名字</th>
                            <th scope="col">类别号</th>
                            <th scope="col">库存</th>
                            <th scope="col">单价</th>
                            <th scope="col">操作</th>
                        </tr>
                    </thead>
            {% for data in  page_obj %}
                    <tbody>
                        <tr>
                            <td scope="row">{{ data.flower_id }}</td>
                            {# 由于我这里遍历的变量是data，所以就是  data.flower_id#}
                            <td>
                                <a href="{% url 'flowers_base:edit_flower' data.flower_id %}">{{ data.flower_name }}</a>
                            </td>
                            <td>
                                <a href="{% url 'flowers_base:class_flower' class_id=data.classi.class_id %}">{{ data.classi.class_id }}</a>
                            </td>
                            <td>{{ data.num }}</td>
                            <td>{{ data.price }}</td>
                            <td class="button_group_in_out">
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <button type="button" class="btn btn-light btn-sm" >
                                        <a class="inbount-btn" href="{% url 'flowers_transcaction:inbound' flower_id=data.flower_id %}">入库</a>
                                    </button>
                                    <button type="button" class="btn btn-light btn-sm">
                                        <a class="outbount-btn" href="{% url 'flowers_transcaction:outbound' flower_id=data.flower_id %}">出库</a>
                                    </button>
                                    <button type="button" class="btn btn-light btn-sm">
                                        <a class="outbount-btn" href="{% url 'flowers_base:delete_flower' data.flower_id %}">删除</a>
                                    </button>
                                    <button type="button" class="btn btn-light btn-sm">
                                        <a class="outbount-btn" href="{% url 'flowers_base:edit_flower' data.flower_id %}">修改</a>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
{#            </div>#}
        {% empty %}
            <li>没有鲜花数据</li>
        {%  endfor %}
            </table>
        </div>
        <div class="row">
            <div class="col-12 d-flex justify-content-start mt-1">
                <nav class="page-dji" aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="{% url 'flowers_base:flower_data' %}?page=1&key={{ key }}" aria-label="Previous">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'flowers_base:flower_data' %}?page={{ page_obj.previous_page_number }}&key={{ key }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                            </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                            </li>
                        {% endif %}
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'flowers_base:flower_data' %}?page={{ page_obj.previous_page_number }}&key={{ key }}">{{ page_obj.previous_page_number }}</a>
                            </li>
                        {% endif %}
                        <li class="page-item active">
                            <a class="page-link" href="#">{{ current_page }}</a>
                        </li>
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'flowers_base:flower_data' %}?page={{ page_obj.next_page_number }}&key={{ key }}">{{ page_obj.next_page_number }}</a>
                            </li>
                        {% endif %}
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'flowers_base:flower_data' %}?page={{ page_obj.next_page_number }}&key={{ key }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Previous">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'flowers_base:flower_data' %}?page={{ paginator.num_pages }}&key={{ key }}" aria-label="Next">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
    </div>
</div>
{% endblock content %}

flowers/flowers_base/templates/flowers_base/index.html
{% extends "flowers_base/base.html" %}

{% block content %}
    <div class="index">
{#        <p>flower_test_systemctl</p>#}
    </div>
{% endblock content %}

flowers/flowers_base/templates/flowers_base/search.html
{% extends 'flowers_base/base.html' %}

{% block content %}
{# 我在APP中的templatetags中创建了三个过滤器，但是我没做完..... #}
{% load custom_tags %}
<div class="container">
    <div class="text-center mt-5 mb-5">
        <h3 class="text-center">搜索{{ key }}</h3>
    </div>
    {% if page_obj %}
        <div  class="container  table-responsive">
        <div class="text-center mt-3 mb-4">
            <h3 class="text-center">鲜花</h3>
        </div>
        <table border="1" class="table text-center table-hover">
            <thead>
            <tr>
                <th scope="col">编号</th>
                <th scope="col">名字</th>
                <th scope="col">类别号</th>
                <th scope="col">库存</th>
                <th scope="col">单价</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
        {% for data in page_obj %}
            {# instanceof查看属于哪个模型#}
            {% if data|isinstanceof_flower%}
                <tbody>
                    <tr>
                        <td scope="row">{{ data.flower_id }}</td>
                        {# 由于我这里遍历的变量是data，所以就是 data.flower_id#}
                        <td>
                            <a href="{% url 'flowers_base:edit_flower' data.flower_id %}">{{ data.flower_name }}</a>
                        </td>
                        <td>
                            <a href="{% url 'flowers_base:class_flower' class_id=data.classi.class_id %}">{{ data.classi.class_id}}</a>
                        </td>
                        <td>{{ data.num }}</td>
                        <td>{{ data.price }}</td>
                        <td class="search_flowers_button_group_in_out">
                            <div aria-label="Basic example" class="btn-group" role="group">
                                <button class="btn btn-light btn-sm" type="button">
                                    <a class="inbount-btn" href="{% url 'flowers_transcaction:inbound' flower_id=data.flower_id %}">入库</a>
                                </button>
                                <button class="btn btn-light btn-sm" type="button">
                                    <a class="outbount-btn"
                                       href="{% url 'flowers_transcaction:outbound' flower_id=data.flower_id %}">出库</a>
                                </button>
                                <button class="btn btn-light btn-sm" type="button">
                                    <a class="outbount-btn" href="{% url 'flowers_base:delete_flower' data.flower_id %}">删除</a>
                                </button>
                                <button class="btn btn-light btn-sm" type="button">
                                    <a class="outbount-btn" href="{% url 'flowers_base:edit_flower' data.flower_id %}">修改</a>
                                </button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            {% endif %}
        {% endfor %}
        </table>
        </div>
    {% else %}
    <div class="search">
        <p>未搜索到</p>
    </div>
    {% endif %}
    {% if page_obj %}
       <div class="container table-responsive">
           <div class="text-center mt-3 mb-4">
                <h3 class="text-center">鲜花类别</h3>
            </div>
            <table border="1" class="table text-center table-hover">
                <thead>
                <tr>
                    <th scope="col">编号</th>
                    <th scope="col">类别名</th>
                    <th scope="col">操作</th>
                </tr>
                </thead>
         {% for data in page_obj %}
            {% if data|isinstanceof_class %}
                    {# 使用for读取从视图文件传入的class_data数据内的数据#}
                    <tbody>
                    <tr>
                        <td scope="row">
                            <a href="{% url 'flowers_base:class_flower' class_id=data.class_id %} ">{{ data.class_id }}</a>
                        </td>
                        <td>
                            <a href="{% url 'flowers_base:edit_class' data.class_id %}">{{ data.class_name }}</a>
                        </td>
                        <td class="class_flower_data_list">
                            <div aria-label="Basic example" class="btn-group" role="group">
                                <button class="btn btn-light btn-sm" type="button">
                                    <a class="inbount-btn" href="{% url 'flowers_base:class_flower' class_id=data.class_id %}">查看</a>
                                </button>
                                <button class="btn btn-light btn-sm delete_class_btn" type="button">
                                    <a class="inbount-btn" href="{% url 'flowers_base:delete_class' data.class_id %}">删除</a>
                                </button>
                                <button class="btn btn-light btn-sm" type="button">
                                    <a class="outbount-btn" href="{% url 'flowers_base:edit_class' data.class_id %}">修改</a>
                                </button>
                            </div>
                        </td>
                    </tr>
                    </tbody>
             {% endif %}
         {% endfor %}
        </table>
        </div>
    {% else %}
            <div class="search">
                <p>未搜索到</p>
            </div>
    {% endif %}
    {% if page_obj %}
        <div class="container  table-responsive">
            <div class="text-center mt-3 mb-4">
                <h3 class="text-center">管理员</h3>
            </div>
            <table border="1" class="table text-center table-hover">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>名字</th>
                    <th>电话</th>
                    <th>操作</th>
                </tr>
                </thead>
        {% for data in page_obj %}
            {% if data|isinstanceof_admin%}
                        <tbody>
                        <tr>
                            <td>
                                <a>{{ data.admin_id }}</a></td>
                            <td>
                                <a href="{% url 'flowers_base:edit_admin' data.admin_id%}">{{ data.admin_name }}</a>
                            </td>
                            <td>{{ data.telephone }}</td>
                            <td class="admin_bound_data">
                                <div aria-label="Basic example" class="btn-group" role="group">
                                    <button class="btn btn-light btn-sm" type="button">
                                        <a class="inbount-btn"
                                           href="{% url 'flowers_transcaction:admin_bond_list' data.admin_id %}">记录</a>
                                    </button>
                                    <button class="btn btn-light btn-sm delete_class_btn" type="button">
                                        <a class="inbount-btn"
                                           href="{% url 'flowers_base:delete_admin' data.admin_id %}">删除</a>
                                    </button>
                                    <button class="btn btn-light btn-sm" type="button">
                                        <a class="outbount-btn"
                                           href="{% url 'flowers_base:edit_admin' data.admin_id %}">修改</a>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        </tbody>
            {% endif %}
        {% endfor %}
                </table>
            </div>
        {% else %}
            <div class="search">
                <p>未搜索到</p>
            </div>
    {% endif %}

</div>
{% endblock %}